include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
   - lib/**/*.g.dart
   - lib/**/*.chopper.dart
#    - lib/**/*.freezed.dart
#    - lib/generated/*
#    - lib/src/api.g.dart

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    flutter_style_todos: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
