name: colourlovers_api
description: A Dart implementation of the COLOURlovers API
version: 1.1.1
repository: https://github.com/albemala/colourlovers-api-dart

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  chopper: ^8.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  chopper_generator: ^8.0.1

  very_good_analysis: ^5.1.0

flutter:
