name: colourlovers_api
description: A comprehensive Flutter wrapper for the COLOURlovers.com API, providing access to colors, palettes, patterns, users, and statistics from the popular color community platform.
version: 2.0.1
repository: https://github.com/albemala/colourlovers-api-dart

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  equatable: ^2.0.7

  json_annotation: ^4.9.0
  chopper: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  chopper_generator: ^8.1.0

  very_good_analysis: ^8.0.0

flutter:
